apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aikas-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/birnazarova/app-chart.git
    path: aikas-app/
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: aikas-app
  syncPolicy:
    automated:
      selfHeal: true