nginxApp:
  replicas: 15
  deploymentName: nginx-app
  containerName: nginx
  image:
    repository: us-central1-docker.pkg.dev/proven-dryad-417822/hello-app/hello-app
    tag: "v2"
  containerPortName: http
  containerPortNumber: 80
  containerTargetPortNumber: 80

serviceAccountName: nginx-service-account

serviceName: nginx-svc