nginxApp:
  replicas: 15
  deploymentName: nginx-app
  containerName: nginx
  image:
    repository: us-central1-docker.pkg.dev/absolute-cubist-432720-a9/app-chart-docker/hello-app
    tag: "v1"
  containerPortName: http
  containerPortNumber: 80
  containerTargetPortNumber: 80

serviceAccountName: nginx-service-account

serviceName: nginx-svc
