apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.nginxApp.deploymentName }}
  labels:
    application: webserver
    managed-by: sre
spec:
  replicas: {{ .Values.nginxApp.replicas }}
  selector:
    matchLabels:
      application: webserver
      managed-by: sre
  template:
    metadata:
      labels:
        application: webserver
        managed-by: sre
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      containers:
        - name: {{ .Values.nginxApp.containerName }}
          image: {{ .Values.nginxApp.image.repository }}:{{ .Values.nginxApp.image.tag }}
          ports:
            - name: {{ .Values.nginxApp.containerPortName }}
              containerPort: {{ .Values.nginxApp.containerPortNumber }}