apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
  labels:
    application: webserver
    managed-by: sre
spec:
  replicas: 3
  selector:
    matchLabels:
      application: webserver
      managed-by: sre
  template:
    metadata:
      labels:
        application: webserver
        managed-by: sre
    spec:
      serviceAccountName: nginx-sa
      containers:
        - name: nginx
          image: us-central1-docker.pkg.dev/proven-dryad-417822/hello-app/hello-app:v2
          ports:
            - name: http
              containerPort: 80