apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
{{- include "commonLabels" . | nindent 4 }}
spec:
  selector:
{{- include "commonLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: 80