apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    application: webserver
    managed-by: sre
spec:
  selector:
    application: webserver
    managed-by: sre
  ports:
    - name: http
      port: 80
      targetPort: 80