name: Validate

on:
    push:
      branches:
        - main
    workflow_dispatch:

jobs:
    validate:
        runs-on: ubuntu-latest

        steps:
        - name: Check out code
        uses: actions/checkout@v3

        - name: Run yamllint
        uses: actionshub/yamllint@v1.8.0