name: YAML Linter

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  
jobs:
  yaml-linter:
    runs-on: ubuntu-latest #sreg-arc-dev
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        # with:
        #   repository: iman-cloudops/sreg-spm-tenants
        #   token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install pip
        run: |
          python -m ensurepip --upgrade
          python -m pip install --upgrade pip

      - name: Install yamllint
        run: pip install yamllint

      - name: Lint YAML files
        run: yamllint . --config-file .yamllint.yml
        