name: validate

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    name: Lint YAML
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install yamllint
      run: pip install yamllint

    - name: Find changed YAML files
      id: find_files
      run: |
        CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E '\.y(a)?ml$' || true)
        echo "::set-output name=files::$CHANGED_FILES"

    - name: Run yamllint
      if: steps.find_files.outputs.files != ''
      run: |
        yamllint ${{ steps.find_files.outputs.files }}